# adding these two removed that dependency conflict (two gems, unirest and another one had different dependency requirements for the same dependency)
# so remember to use bundler!!!! (gemfile)
require "rubygems" 
require "bundler/setup"

require 'uri'
require 'anemone'
require 'pry'
require_relative 'data'
require_relative 'tld_list'
require_relative 'get_domain_function'
require 'global_phone'
GlobalPhone.db_path = 'global_phone.json'
require 'unirest'
require 'redis'
require 'redis-namespace'




domains = [


'http://feebee.com.tw',
'http://countryrebel.com',
'http://nylon.com',
'http://spigen.com',
'http://freshmenu.com',
'http://citiesocial.com',
'http://postergully.com',
'http://elitify.com',
'http://funko.com',
'http://hawkersco.com',
'http://mvmtwatches.com',
'http://yankodesign.com',
'http://shopmissa.com',
'http://kaylaitsines.com',
'http://morphebrushes.com',
'http://kithnyc.com',
'http://bajaao.com',
'http://boardwalkbuy.com',
'http://fashionnova.com',
'http://shoeme.ca',
'http://makershed.com',
'http://muse-themes.com',
'http://trytheworld.com',
'http://teeturtle.com',
'http://hipvan.com',
'http://toneitup.com',
'http://triangl.com',
'http://blackmilkclothing.com',
'http://basicswallet.com',
'http://fetchapp.com',
'http://mondotees.com',
'http://bungiestore.com',
'http://anovaculinary.com',
'http://powdercity.com',
'http://tumbleweedhouses.com',
'http://jcktrend.com',
'http://shethinx.com',
'http://kangeronline.com',
'http://case-mate.com',
'http://hengedocks.com',
'http://3claps.com',
'http://seedsforafrica.co.za',
'http://getkeysmart.com',
'http://greats.com',
'http://litographs.com',
'http://wyo.in',
'http://headphone.com',
'http://chubbiesshorts.com',
'http://asmaraku.com',
'http://onlineprasad.com',
'http://shopbando.com',
'http://qalo.com',
'http://dftba.com',
'http://turntablelab.com',
'http://tortugabackpacks.com',
'http://allyouneedfresh.cn.com',
'http://brands4all.com.gr',
'http://mmawarehouse.com',
'http://drgrab.com',
'http://fjallraven.us',
'http://100percentpure.com',
'http://dodocase.com',
'http://knoxlabs.com',
'http://headphonezone.in',
'http://thekewlshop.com',
'http://asgoodasnew.com',
'http://shopatplaces.com',
'http://jackerwin.com',
'http://yellowfashion.in',
'http://sneakerpolitics.com',
'http://ivoryella.com',
'http://hardgraft.com',
'http://shopjeen.com',
'http://bellamihair.com',
'http://tulababycarriers.com',
'http://sharkrobot.com',
'http://chicagomusicexchange.com',
'http://imbesharam.com',
'http://leuxonghoi.com',
'http://go-iaso.com',
'http://peachandlily.com',
'http://meowingtons.com',
'http://edensgarden.com',
'http://exportleftovers.com',
'http://kleankanteen.com',
'http://tattly.com',
'http://sokoglam.com',
'http://cosmetic-love.com',
'http://2modern.com',
'http://catholicexchange.com',
'http://rageon.com',
'http://stylishbazaar.com',
'http://getinkbox.com',
'http://johnnyshades.com',
'http://cupshe.com',
'http://shopzerouv.com',
'http://denydesigns.com',
'http://florencescoveljewelry.com',
'http://valuecart.in',
'http://lifx.com',
'http://gpen.com',
'http://outofthesandbox.com',
'http://skinnydiplondon.com',
'http://popchartlab.com',
'http://featuresneakerboutique.com',
'http://homage.com',
'http://sevenly.org',
'http://urbanarmorgear.com',
'http://musewidgets.com',
'http://go-clair.com',
'http://polerstuff.com',
'http://rowdygentleman.com',
'http://thepostbox.in',
'http://eliquid.com',
'http://bdgastore.com',
'http://oipolloi.com',
'http://untuckit.com',
'http://sudara.org',
'http://emilyley.com',
'http://survivalfrog.com',
'http://wolfnoir.com',
'http://mizzue.com',
'http://topodesigns.com',
'http://soloshot.com',
'http://ashleybridget.com',
'http://pixiefaire.com',
'http://thepoptoy.com',
'http://fragrantjewels.com',
'http://drgrab.com.au',
'http://kidrobot.com',
'http://hickies.com',
'http://fashionequation.com',
'http://hellonomad.com',
'http://dollboxx.com.au',
'http://gamershop.com.mx',
'http://craneandcanopy.com',
'http://evolutivelabs.com',
'http://sivanaspirit.com',
'http://sochstudio.com',
'http://planetbox.com',
'http://dropdead.co',
'http://cotopaxi.com',
'http://boardgamegeekstore.com',
'http://packershoes.com',
'http://streetmoda.com',
'http://mightycarmods.com',
'http://abookapart.com',
'http://zooshoo.com',
'http://casadocodigo.com.br',
'http://dropkaffe.com',
'http://boombycindyjoseph.com',
'http://tannergoods.com',
'http://dealman.co.nz',
'http://outofprintclothing.com',
'http://osomwear.com',
'http://dizinga.com',
'http://vfbpro.com',
'http://itokri.com',
'http://beardbrand.com',
'http://myrume.com',
'http://statebicycle.com',
'http://popuptee.com',
'http://cellrizon.com',
'http://bluesmart.com',
'http://harrisfarm.com.au',
'http://burkedecor.com',
'http://massappeal.com',
'http://lollywollydoodle.com',
'http://shoreprojects.com',
'http://fittea.com',
'http://hellomerch.com',
'http://caseologycases.com',
'http://taylorstitch.com',
'http://distintos.com.br',
'http://budovideos.com',
'http://whiteplum.com',
'http://scamstuff.com',
'http://yourtea.com',
'http://luxyhair.com',
'http://whistle.com',
'http://onceuponatee.net',
'http://seiyajapan.com',
'http://despair.com',
'http://zopella.com',
'http://glitty.co',
'http://stampd.com',
'http://missionbelt.com',
'http://mostlymusic.com',
'http://vaporauthority.com',
'http://shoppriceless.com',
'http://livelovepolish.com',
'http://fresh-tops.com',
'http://goldentipstea.com',
'http://drsebiscellfood.com',
'http://anovos.com',
'http://parachutehome.com',
'http://fiebigershoes.com',
'http://almarazrecords.com',
'http://biolitestove.com',
'http://deathwishcoffee.com',
'http://poweruptoys.com',
'http://deadstock.ca',
'http://ejuices.com',
'http://fiveminutejournal.com',
'http://quayaustralia.com',
'http://poketo.com',
'http://orthofeet.com',
'http://jlabaudio.com',
'http://bebe2go.com',
'http://vanguardmil.com',
'http://rains.dk',
'http://teradek.com',
'http://quickmobilefix.com',
'http://shopdashonline.com',
'http://andbanana.com',
'http://macmerise.com',
'http://shopnaari.com',
'http://indiasarihouse.com',
'http://pavlok.com',
'http://earthmamaangelbaby.com',
'http://alphaleteathletics.com',
'http://shoptoneitup.com',
'http://muraboutique.com.au',
'http://boardgamebliss.com',
'http://thuglifeshirts.com',
'http://wholesalefashionshoes.com',
'http://posterguy.in',
'http://bazzzar.com',
'http://mylesapparel.com',
'http://downeastbasics.com',
'http://thatshirtwascash.com',
'http://tentsile.com',
'http://trihold.com',
'http://solarisjapan.com',
'http://thisisground.com',
'http://romanatwood.com',
'http://emilymcdowell.com',
'http://ministryofsupply.com',
'http://twenty3.my',
'http://quadlockcase.com',
'http://italianbarber.com',
'http://whatsawaist.com',
'http://opsgear.com',
'http://ideasanddiscoveries.com',
'http://representclothing.co.uk',
'http://bbolder.com',
'http://futurelight.co.za',
'http://screamingowl.com',
'http://cocowhite.com',
'http://pursebox.ca',
'http://mychoicesoftware.com',
'http://forhumanpeoples.com',
'http://buymebrunch.com',
'http://sanshee.com',
'http://beckyhiggins.com',
'http://mouth.com',
'http://buypeel.com',
'http://uvgrab.com',
'http://mymakeupbrushset.com',
'http://gogreensolar.com',
'http://themarkhor.com',
'http://houseoflashes.com',
'http://leifshop.com',
'http://nicelaundry.com',
'http://47brand.com',
'http://niqoo.com',
'http://kookai.com.au',
'http://mooreaseal.com',
'http://bentoandco.com',
'http://telescopes.com',
'http://eyeheartworld.org',
'http://tiberis.ru',
'http://tribesports.com',
'http://daintyhooligan.com',
'http://redditmarket.com',
'http://blipshift.com',
'http://wetdog.com.au',
'http://radiantbay.com',
'http://designaglow.com',
'http://seektheuniq.com',
'http://keepgo.com',
'http://usamilitarymedals.com',
'http://colossalshop.com',
'http://localvape.com',
'http://gravitypope.com',
'http://skinny-teatox.com',
'http://brilliant.co',
'http://eluxurysupply.com',
'http://rarerabbit.in',
'http://nationalparksdepot.us',
'http://aftershokz.com',
'http://killstar.com',
'http://tnuck.com',
'http://maggiescrochet.com',
'http://inuinu.com',
'http://melimelo.com',
'http://naiise.com',
'http://freshlypicked.com',
'http://johnnycupcakes.com',
'http://studiobananathings.com',
'http://inkwellpress.com',
'http://smokonow.com',
'http://occmakeup.com',
'http://aetherapparel.com',
'http://reelstyle.co',
'http://atisundar.com',
'http://ridgewallet.com',
'http://victoriaemerson.com',
'http://2020ave.com',
'http://visitaorlandoflorida.com',
'http://cheapestnatostraps.com',
'http://southerntots.com',
'http://orbitkey.com',
'http://neuegalerie.org',
'http://rootsoffight.com',
'http://getcairn.com',
'http://20x200.com',
'http://thejojobacompany.com.au',
'http://fcpeffects.com',
'http://toywars.com',
'http://furiouspete.com',
'http://theghostlystore.com',
'http://thelasthunt.com',
'http://skybell.com',
'http://tacticaldistributors.com',
'http://americanlasercrafts.com',
'http://clickandgrow.com',
'http://alicebow.com',
'http://lacolombe.com',
'http://jolynclothing.com',
'http://thegymlifestyle.com',
'http://lostartpress.com',
'http://marcuslemonis.com',
'http://timhughesuvcodes.com',
'http://nonda.co',
'http://apt2b.com',
'http://beautycrowd.com',
'http://matefit.me',
'http://spondoolies-tech.com',
'http://indofash.com',
'http://gfuel.com',
'http://bootea.com',
'http://snydepels.dk',
'http://virginvapor.com',
'http://biisafe.com',
'http://jurawatches.co.uk',
'http://tantusinc.com',
'http://seemecnc.com',
'http://thehobbywarehouse.co.nz',
'http://expirit.es',
'http://3sixteen.com',
'http://shopatshowcasecanada.com',
'http://themightymug.com',
'http://ideou.com',
'http://threebirdnest.com',
'http://survivalstraps.com',
'http://misshamptons.com',
'http://tenslife.com',
'http://petngo.com.mx',
'http://travelkhushi.com',
'http://xgaming.com',
'http://evannex.com',
'http://alameda.mx',
'http://fazeclanstore.com',
'http://rsvpgallery.com',
'http://unofficialcardboard.com',
'http://richardsherman25.com',
'http://cargo-works.com',
'http://buybluesteel.com',
'http://naja.co',
'http://leibal.com',
'http://assassinshoodies.com',
'http://shopbeckyhiggins.com',
'http://atmosfx.com',
'http://modmic.com',
'http://laconicum.com',
'http://fendrihan.ca',
'http://beyondbasick.com',
'http://textualtees.com',
'http://quinceandco.com',
'http://outgrow.me',
'http://bay-57.net',
'http://smsaudio.com',
'http://variationfashion.com',
'http://mantraband.com',
'http://whatsinthebible.com',
'http://jakeweidmann.com',
'http://shop.mg.co.uk',
'http://skinnymetea.com.au',
'http://8case.net',
'http://1861.ca',
'http://shinesty.com',
'http://1shirt.com',
'http://wizardpuff.com',
'http://johnelliott.co',
'http://naturalbabyshower.co.uk',
'http://bugasalt.com',
'http://masterdynamic.com',
'http://wickedclothes.com',
'http://t-shirtmagazineonline.com',
'http://royaldesignstudio.com',
'http://thehomet.com',
'http://sthsweet.com',
'http://highonleather.com',
'http://the7line.com',
'http://belovedshirts.com',
'http://linjer.co',
'http://spyguysecurity.com',
'http://oneness287.com',
'http://themaker.fr',
'http://criticalcycles.com',
'http://blenderseyewear.com',
'http://craftandvision.com',
'http://fatbeats.com',
'http://innertubeshop.com',
'http://iamnotbasic.com',
'http://joujou.com.au',
'http://cititrends.com',
'http://lightningvapes.com',
'http://toddsnyder.com',
'http://therooststand.com',
'http://fabmart.com',
'http://9five.com',
'http://mypichi.com',
'http://stylefiesta.com',
'http://gramovox.com',
'http://snowpeak.com',
'http://geekhoodies.com',
'http://teehood.com',
'http://gentrynyc.com',
'http://gorgeye.com',
'http://modifywatches.com',
'http://crooksncastles.com',
'http://beautyrevng.com',
'http://angelusdirect.com',
'http://solesupremacy.com',
'http://furbishstudio.com',
'http://embelle.com.mx',
'http://cherrydiva.co.uk',
'http://meltcosmetics.com',
'http://finnishbabybox.co',
'http://olaplex.com',
'http://saddlebackresources.com',
'http://inkkas.com',
'http://shoplostfound.com',
'http://jaycotts.co.uk',
'http://fivesimplesteps.com',
'http://manoutfitters.com',
'http://yeezysupply.com',
'http://foresightopticals.in',
'http://xeniaboutique.com.au',
'http://josephnogucci.com',
'http://dsptch.com',
'http://naturalstacks.com',
'http://hazelandolive.com',
'http://daylightcurfew.com',
'http://boardwalkbuy.co.uk',
'http://ripndipclothing.com',
'http://originalsoegear.com',
'http://thetrendzvenue.com',
'http://areaware.com',
'http://getdubs.com',
'http://dearkates.com',
'http://ubiome.com',
'http://drgrab.co.uk',
'http://shop.cba.org',
'http://venomarmor.com',
'http://ironandresin.com',
'http://fashionclaw.com',
'http://glowrecipe.com',
'http://andrebadi.com',
'http://100lot.com',
'http://spool72.com',
'http://shopimpressions.com',
'http://lovevsdesign.com',
'http://perthmobility.com',
'http://pictureline.com',
'http://rusticcuff.com',
'http://evolutivelabs.com.tw',
'http://inkedgaming.com',
'http://somethingsweet.com.tw',
'http://weusepp.com',
'http://valfre.com',
'http://nyrb.com',
'http://roddandgunn.com',
'http://elwoodclothing.com',
'http://goodasgold.co.nz',
'http://aninebing.com',
'http://canvashomestore.com',
'http://qwerkywriter.com',
'http://nisolo.com',
'http://youfoodz.com',
'http://thintea.com.au',
'http://italiancatch.nl',
'http://seedsnow.com',
'http://bublcam.com',
'http://qmxonline.com',
'http://idecorateshop.com',
'http://pinkdolphinonline.com',
'http://epauletnewyork.com',
'http://suzannesomers.com',
'http://cleanthemes.co.uk',
'http://ejuices.co',
'http://beefriendlyskincare.com',
'http://tabtag.com',
'http://standdesk.co',
'http://harrypotterplatform934.com',
'http://vapoureyes.com.au',
'http://ridemarbel.com',
'http://hennessyhammock.com',
'http://stikwood.com',
'http://kweliclub.com',
'http://thegstreet.com',
'http://nisaeurope.com',
'http://sleefs.com',
'http://clarev.com',
'http://melondipity.com',
'http://totebagfactory.com',
'http://ibushak.com',
'http://billowby.com',
'http://banglewale.com',
'http://onlineshopping.pt',
'http://luxedh.com',
'http://baseqi.com',
'http://heidisongs.com',
'http://happywatching.com',
'http://carrislabelle.com',
'http://zellestudio.com',
'http://bourbonandboots.com',
'http://blendsus.com',
'http://thehorse.com.au',
'http://5mr.com',
'http://backtotheroots.com',
'http://petitvour.com',
'http://ingeniamuebles.com.mx',
'http://thickassglass.com',
'http://wtb.com',
'http://freetronics.com.au',
'http://drgrab.co.nz',
'http://spiritualgangster.com',
'http://organiccottonplus.com',
'http://gosunstove.com',
'http://named.com.au',
'http://tayroc.com',
'http://phoenixartisanaccoutrements.com',
'http://flagnorfail.com',
'http://promate.net',
'http://merchconnectioninc.com',
'http://zurchers.com',
'http://kendalhyde.com',
'http://whippingpost.com',
'http://vorana.mx',
'http://minaal.com',
'http://geveystore.com',
'http://zboardshop.com',
'http://sugarpillshop.com',
'http://abigailahern.com',
'http://churchmouseyarns.com',
'http://shopsweetlulu.com',
'http://zokuhome.com',
'http://cvdirectomexico.com',
'http://hiannie.com',
'http://get-supplied.com',
'http://vapevetstore.com',
'http://modishstore.com',
'http://shopriffraff.com',
'http://indiasarihouse.co.in',
'http://sprezzabox.com',
'http://vsnmobil.com',
'http://hallmarkcards.co.in',
'http://cctv-direct.co.za',
'http://jenshansen.com',
'http://cbldf.org',
'http://mollusksurfshop.com',
'http://helbak.com',
'http://atomikrc.com',
'http://proozy.com',
'http://kenu.com',
'http://chefd.com',
'http://handeyesupply.com',
'http://goodnightmacaroon.co',
'http://fisherwallace.com',
'http://honeybirdette.com',
'http://meragarden.com',
'http://trustbasket.com',
'http://oreeartisans.com',
'http://brooklinen.com',
'http://poprageous.com',
'http://nestbedding.com',
'http://geniuspack.com',
'http://ilovedooney.com',
'http://riptrippers.com',
'http://greenroninstore.com',
'http://wildflowercases.com',
'http://drgrab.ca',
'http://seavees.com',
'http://dagnedover.com',
'http://easyskinz.com',
'http://mstrwatches.com',
'http://originalgrain.com',
'http://firstfixdental.com',
'http://lstnsound.co',
'http://tudors-tr.com',
'http://goldieblox.com',
'http://uoionline.com',
'http://deeringbanjos.com',
'http://spikeball.com',
'http://cosmeticoutlet.nl',
'http://contagious.com',
'http://rightchannelradios.com',
'http://baronfig.com',
'http://skywalkersusa.com',
'http://spreepicky.com',
'http://peterdobias.com',
'http://jennypackham.com',
'http://hairburst.com',
'http://yoobi.com',
'http://theperfumelounge.com',
'http://artofplay.com',
'http://sleepingbaby.com',
'http://sakaralife.com',
'http://micro-motor-warehouse.com',
'http://fringesport.com',
'http://lightleaklove.com',
'http://sprayable.co',
'http://amuze.com',
'http://frenzyfifa.com',
'http://milktee.nu',
'http://sugarpaper.com',
'http://uistencils.com',
'http://nineteeneightyeight.com',
'http://snowboardaddiction.com',
'http://florencescoveljewelry.co.uk',
'http://flykly.com',
'http://highnoteperformance.com',
'http://skicks.com',
'http://alimapure.com',
'http://lavishshoestring.com',
'http://organicburst.com',
'http://thecolorpopshop.com',
'http://bynifty.com',
'http://caseofmine.com',
'http://feministapparel.com',
'http://greyhaze.co.uk',
'http://esther.com.au',
'http://oompa.com',
'http://revolights.com',
'http://tothestars.media',
'http://manoftheworld.com',
'http://bellacandles.com',
'http://beaconscloset.com',
'http://activefaithsports.com',
'http://thegivingkeys.com',
'http://urbanstox.com',
'http://soundiron.com',
'http://lawnfawn.com',
'http://youngandreckless.com',
'http://oberondesign.com',
'http://migoals.com',
'http://syndromestore.com',
'http://ckie.com',
'http://somethinggreek.com',
'http://laurenjames.com',
'http://elephonemobile.com',
'http://officialhodgetwins.com',
'http://svgstudio.com',
'http://starlooks.com',
'http://vapetrik.com',
'http://fastwrx.com',
'http://rmsbeauty.com',
'http://rhoneapparel.com',
'http://premierh2o.com',
'http://closetcandyboutique.com',
'http://ecolifeglobal.com',
'http://thebrotherscut.com',
'http://msmbox.com',
'http://justenaj.com',
'http://missionathletecare.com',
'http://latiendadefrida.com',
'http://studioneat.com',
'http://dahlia.com',
'http://tweed.com',
'http://keyboard.io',
'http://nyfashioncenterfabrics.com',
'http://tamarcollection.com',
'http://houseofholland.co.uk',
'http://caudabe.com',
'http://annchery.com.co',
'http://rggedu.com',
'http://we-wood.us',
'http://powiscustom.com',
'http://ballandbuck.com',
'http://lampsusa.com',
'http://shopsincerelyjules.com',
'http://notre-shop.com',
'http://beltology.com',
'http://tightstore.com',
'http://maryengelbreit.com',
'http://iheartguts.com',
'http://linusbike.com',
'http://ilycouture.com',
'http://blotchwear.com',
'http://solebicycles.com',
'http://kanvape.com',
'http://stampstampede.org',
'http://skoaktiebolaget.se',
'http://gojiaccess.com',
'http://teardropshop.com',
'http://twsbi.com',
'http://velvetcloud.com',
'http://florists.com',
'http://aceraft.com',
'http://maramani.com',
'http://luxire.com',
'http://ishine365.com',
'http://hiphopdrumsamples.com',
'http://seasonwithspice.com',
'http://catholicshopping.com',
'http://wallsneedlove.com',
'http://shopdixi.com',
'http://hiutdenim.co.uk',
'http://beadshop.com',
'http://laguiole-imports.com',
'http://tamrac.com',
'http://ledconceptslighting.com',
'http://junglejims.com',
'http://blancgroup.com',
'http://blackboxmycar.com',
'http://claudiaandjulia.com',
'http://kollectionk.com',
'http://hukgear.com',
'http://passiondelivery.com',
'http://banjoandmatilda.com.au',
'http://taylorbrandsllc.com',
'http://nomadshop.net',
'http://reelsteady.com',
'http://fransboonestore.com',
'http://ninostyle.com',
'http://premadepaleo.com',
'http://holstedjewelers.com',
'http://p31bookstore.com',
'http://theunbrandedbrand.com',
'http://flyingrobot.co',
'http://shopangl.com',
'http://shelfies.com',
'http://bottlekeeper.com',
'http://lauraashleyusa.com',
'http://paulevansny.com',
'http://oemautopartsco.com',
'http://slimwalletjunkie.com',
'http://uniquecoolyou.com',
'http://phanteksusa.com',
'http://natostrapsco.com',
'http://beastmodejonescoaching.com',
'http://upperplayground.com',
'http://machusonline.com',
'http://mcmexpostore.com',
'http://sugarfina.com',
'http://fonesalesman.com',
'http://soloartesmarciales.com',
'http://michaelstokes.net',
'http://pumpchasersclothing.com',
'http://trendyholic.com',
'http://ultykhopdi.com',
'http://ishop.gt',
'http://tepayi.com',
'http://rockwelltime.com',
'http://heromart.com',
'http://canadadashcam.com',
'http://catalystlifestyle.com',
'http://thewodlife.com.au',
'http://furlscrochet.com',
'http://woodysfurniture.in',
'http://kamerar.com',
'http://corkcicle.com',
'http://prometheusdesignwerx.com',
'http://dolluxe.com',
'http://angesdesucre.com',
'http://fanshophq.com',
'http://suavecitopomade.com',
'http://froy.com',
'http://hawkersaustralia.com',
'http://electronicstix.com',
'http://theweddingofmydreams.co.uk',
'http://rodengray.com',
'http://coldcutsmerch.com',
'http://jamstik.com',
'http://thelittlemarket.com',
'http://flattummytea.com',
'http://cadencecollection.com',
'http://hawkers.co',
'http://semihandmadedoors.com',
'http://sockdrawer.com',
'http://bikiniluxe.com',
'http://essentialoil.com',
'http://ecoatheart.com',
'http://modern-citizen.com',
'http://howtodrawmanga.com',
'http://wantmylook.com',
'http://brunton.com',
'http://gozrim.co.il',
'http://excalibur-publishing.com',
'http://vitalydesign.com',
'http://bitemyapple.co',
'http://craftshack.com',
'http://missbabs.com',
'http://shopdressup.com',
'http://rhinocameragear.com',
'http://unitedbyblue.com',
'http://mykinderpack.com',
'http://iloveapparel.com',
'http://labellamafiaclothing.com',
'http://heygorgeous.com',
'http://dreamqii.com',
'http://elevationlab.com',
'http://jomers.com',
'http://haircity.co.za',
'http://byhandlondon.com',
'http://sublimestitching.com',
'http://hickies.eu',
'http://ilovejewelryauctions.com',
'http://dreamclosetcouture.us',
'http://mivinteriores.com',
'http://treesforachange.com',
'http://harempants.com',
'http://breazy.com',
'http://kiniki.com',
'http://ripstopbytheroll.com',
'http://mollaspace.com',
'http://healingsolutions.com',
'http://bodylastics.com',
'http://binoculars.com',
'http://iwantproof.com',
'http://opinel-usa.com',
'http://efuktshirts.com',
'http://covalvapes.com',
'http://ephin.com',
'http://stylingyoushop.com.au',
'http://worldwide-marijuana-seeds.com',
'http://biopop.com',
'http://electricfamily.com',
'http://egopowerplus.com',
'http://adirondackvapor.com',
'http://reservestrap.com',
'http://basmatik.com',
'http://capecoffeebeans.co.za',
'http://chasingpaper.com',
'http://arcticfoxhaircolor.com',
'http://zoomhash.com',
'http://hasbean.co.uk',
'http://ylcamera.com.my',
'http://soundbot.com',
'http://getonfleek.com',
'http://umoro.com',
'http://sweetpetescandy.com',
'http://colouryoureyes.com',
'http://canadaluggagedepot.ca',
'http://eveandtribe.com',
'http://rebdolls.com',
'http://yellowleafhammocks.com',
'http://xterrawetsuits.com',
'http://makerskit.com',
'http://oliviatheshop.com',
'http://lunasandals.com',
'http://refurb.io',
'http://ifandco.com',
'http://manieredevoir.com',
'http://longsjewelers.com',
'http://telugubooks.in',
'http://bactrack.com',
'http://hauslondon.com',
'http://electricstyles.com',
'http://battlefieldvegas.com',
'http://sandcloudapparel.com',
'http://megannielsen.com',
'http://raygunsite.com',
'http://skratchlabs.com',
'http://brosupps.com',
'http://armyandoutdoors.co.nz',
'http://mifitness.co.za',
'http://viberg.com',
'http://y-r-u.com',
'http://dicksbymail.com',
'http://echoclubhouse.com',
'http://calmtheham.com',
'http://jenspiratebooty.com',
'http://bentology.net',
'http://shoptherage.com',
'http://alflahertys.com',
'http://sportiquesf.com',
'http://clearspring.co.uk',
'http://stargazejewelry.com',
'http://suredesigntshirts.com',
'http://kiddietowns.com',
'http://wanderlustandco.com',
'http://tailgateclothing.com',
'http://shophearts.com',
'http://costumeish.com',
'http://digitalprojectlife.com',
'http://distilunion.com',
'http://vapedojo.com',
'http://wornstar.com',
'http://mobywrap.com',
'http://sourcevapes.com',
'http://sundancebeach.com',
'http://machine-era.com',
'http://campnocounselors.com',
'http://ca.soyoung.ca',
'http://paradiseoils.com',
'http://leadershipiq.com',
'http://pooparcel.com',
'http://ballabracelets.com',
'http://pinwheeljewels.com',
'http://southernmarsh.com',
'http://forged.com',
'http://order2india.com',
'http://hereplus.me',
'http://fuzdesigns.com',
'http://holdfastgear.com',
'http://fuckingawesomestore.com',
'http://itfit.com',
'http://maxsparrow.com.au',
'http://mybrand.shoes',
'http://carvinaudio.com',
'http://besamecosmetics.com',
'http://suprgood.com',
'http://shopjetstream.com',
'http://80percentarms.com',
'http://weirdape.com',
'http://joyfulnoiserecordings.com',
'http://luminaid.com',
'http://mikayogawear.com',
'http://activeedgegear.com',
'http://norcom.com.au',
'http://soshape.com',
'http://abubot.ph',
'http://shopifyconcierge.com',
'http://gotopatterns.com',
'http://vapesocietysupply.com',
'http://plussizefix.com',
'http://batterybro.com',
'http://anherb.com',
'http://namastevapes.co.uk',
'http://distortedpeople.com',
'http://boredparacord.com',
'http://ministryofbritishcomedy.com',
'http://noveske.com',
'http://goodfuckingdesignadvice.com',
'http://overtone.co',
'http://speedcube.com.au',
'http://pipsnacks.com',
'http://iedm.com',
'http://shoemeoutlet.ca',
'http://themeadow.com',
'http://izola.com',
'http://thefowndry.com',
'http://bluffworks.com',
'http://theharvardshop.com',
'http://railsclothing.com',
'http://sparkleinpink.com',
'http://gmyle.com',
'http://boysdontcry.co',
'http://hipknoties.com',
'http://awesomeworld.co.uk',
'http://woolandprince.com',
'http://carryacountry.com',
'http://nearlynewlywed.com',
'http://elizabethcraftdesigns.com',
'http://collagevideo.com',
'http://jacklinks.com',
'http://puplife.com',
'http://jennibick.com',
'http://calamityware.com',
'http://daytonatactical.com',
'http://microapps.com',
'http://ilumi.co',
'http://jewelove.in',
'http://patagoniaprovisions.com',
'http://swpea.com',
'http://vaporjedi.com',
'http://dappertime.com',
'http://hautehijab.com',
'http://pamelalovenyc.com',
'http://shopthefinest.com',
'http://thegifshop.net',
'http://petermanningnyc.com',
'http://rangrage.in',
'http://analogueinteractive.com',
'http://childrens-ministry-deals.com',
'http://spicely.com',
'http://shopninecrows.com',
'http://panateamatcha.com',
'http://ambronite.com',
'http://genuine-people.com',
'http://craftly.com',
'http://bottlecutting.com',
'http://fizzygoblet.com',
'http://sugarcosmetics.com',
'http://24hundred.net',
'http://bravoconcealment.com',
'http://albertotorresi.com',
'http://kennedyblue.com',
'http://ejuicedirect.com',
'http://americanbarbell.com',
'http://thesnookishop.com',
'http://sundaysomewhere.com',
'http://zelda-symphony.com',
'http://stoneisland.co.uk',
'http://ghostandstars.com',
'http://shop-milkyway.com',
'http://boreasgear.com',
'http://usbtypewriter.com',
'http://mygekks.com',
'http://loftresumes.com',
'http://degrendel.co.za',
'http://mnzstore.com',
'http://falseeyelashes.co.uk',
'http://air-purifiers-america.com',
'http://topgirl.com.my',
'http://clarklittlephotography.com',
'http://theshoelink.com.au',
'http://skinnyfoxdetox.com',
'http://hcgart.com',
'http://banishacnescars.com',
'http://nomiku.com',
'http://bestchoiceproducts.com',
'http://danishdesignstore.com',
'http://hellomatchatea.com',
'http://nyko.com',
'http://wintercroft.com',
'http://livingdeal.com',
'http://zaraterez.com',
'http://thestylebrothers.com',
'http://armtheanimals.com',
'http://rokasports.com',
'http://instanatural.com',
'http://africanmusicbuy.com',
'http://novanatural.com',
'http://watchobsession.co.uk',
'http://graphenea.com',
'http://patioorganico.mx',
'http://veloink.com',
'http://fantasyjocks.com',
'http://mohawkgeneralstore.com',
'http://evercut.jp',
'http://parvane.net',
'http://ootdfash.com',
'http://mindshiftgear.com',
'http://hirschstraps.com',
'http://axisdrones.com',
'http://thenophone.com',
'http://merchology.com',
'http://stayclassy.no',
'http://hotmilklingerie.com',
'http://eazywallz.com',
'http://ruindays.com',
'http://abbyshot.com',
'http://guavafamily.com',
'http://skystreamx.com',
'http://thevaporchef.com',
'http://megadiscountstore.com.sg',
'http://nialaya.com',
'http://vraiandoro.com',
'http://shopvida.com',
'http://campusprotein.com',
'http://rabbitair.com',
'http://flyingmouse365.com',
'http://patriciafield.com',
'http://empiremedals.com',
'http://gaffgun.com',
'http://gusmodern.com',
'http://hierbasorganicas.com.mx',
'http://mechanicaldummy.com',
'http://multirotorheli.ca',
'http://banjoandmatilda.com',
'http://puffco.com',
'http://normakamali.com',
'http://blackroll.de',
'http://thefastflicks.com',
'http://shaverevolution.com',
'http://malacollective.com',
'http://barefootprovisions.com',
'http://kix-files.com',
'http://makergear.com',
'http://func.net',
'http://bexargoods.com',
'http://assemblynewyork.com',
'http://idsmartphone.com.my',
'http://gothiclolitawigs.com',
'http://marlasfashions.com',
'http://memobottle.com',
'http://lugol.com',
'http://lordtimepieces.com',
'http://laserlyte.com',
'http://toiee.jp',
'http://supplyandadvise.com',
'http://e-panneur.ca',
'http://kenanddanadesign.com',
'http://emojistickers.com',
'http://justwow.co.nz',
'http://wearcommando.com',
'http://pand.co',
'http://areyouami.com',
'http://bestowed.com',
'http://trendlee.com',
'http://donnadowney.com',
'http://closetdiaries.in',
'http://lehighdefense.com',
'http://cwpencils.com',
'http://kidzinc.com.au',
'http://modshop1.com',
'http://infantino.com',
'http://pursuefitness.co.uk',
'http://pintrill.com',
'http://fullthrottlesaloon.com',
'http://flowersinmind.com',
'http://firecrackerusa.com',
'http://thejojobacompany.com',
'http://activeautowerke.com',
'http://barristerandmann.com',
'http://ledflashlights.in',
'http://theproducerschoice.com',
'http://peachesandpetals.com',
'http://parinita.co.in',
'http://namepage.com',
'http://groovytrend.com',
'http://komodokamado.com',
'http://currenwatches.com',
'http://folgertech.com',
'http://showponi.com',
'http://cherryaffairs.com',
'http://teaave.com',
'http://sobrebarba.com.br',
'http://eyesonwalls.com',
'http://triple-t-studios.com',
'http://solematesneakers.com',
'http://oneupcomponents.com',
'http://roseshire.com',
'http://theuvcollector.com',
'http://pestlemortarclothing.com',
'http://bigcuplittlecup.com',
'http://veestro.com',
'http://sipsnap.com',
'http://paracable.com',
'http://thegreat-divide.com',
'http://bombayhair.com',
'http://vsslgear.com',
'http://coolgalblue.com',
'http://sparkleskirts.com',
'http://shopboxbasics.com',
'http://tomboyx.com',
'http://unisnewyork.com',
'http://laracaseyshop.com',
'http://stealthgearusa.com',
'http://walletwall.com',
'http://shirtlessapparel.com',
'http://sub-shop.com',
'http://colorcord.com',
'http://capsuletoronto.com',
'http://1800cinchers.com',
'http://zoumzoumparty.com',
'http://sturdiproducts.com',
'http://kiini.com',
'http://dueltek.com.au',
'http://thesill.com',
'http://mimiberry.co.uk',
'http://shopredone.com',
'http://thesuperheroines.com',
'http://cheapcookiecutters.com',
'http://searchmymobile.in',
'http://abcprintsupplies.com.au',
'http://beethinking.com',
'http://treatadog.com',
'http://bbcicecream.eu',
'http://sensualove.com',
'http://wodsuperstore.com',
'http://haircompounds.com',
'http://tangled.co.za',
'http://spreadshoes.com',
'http://insaraf.com',
'http://sdsnation.com',
'http://vodelle.com',
'http://rockanutrition.de',
'http://touchzerogravity.com',
'http://jackandjillboutique.com',
'http://mosbowsmemphis.com',
'http://shopzenpencils.com',
'http://treatstream.com',
'http://drvita.com',
'http://craftcarrot.com',
'http://huel.me',
'http://rogueguitarshop.com',
'http://pontoonstuff.com',
'http://ragingheroes.com',
'http://jmandsons.com',
'http://secretingredient.com.hk',
'http://laptoplunches.com',
'http://soymacho.com',
'http://sriracha2go.com',
'http://wordnotebooks.com',
'http://bottleneckgallery.com',
'http://jbweld.com',
'http://oliversapparel.com',
'http://whitebohemian.com.au',
'http://blackartdepot.com',
'http://velvetcaviar.com',
'http://bunkbedking.com',
'http://bp4uphotographerresources.com',
'http://soundfreaq.com',
'http://liquormart.co.nz',
'http://faucetface.com',
'http://studioproper.com',
'http://purecitycycles.com',
'http://drsquatch.com',
'http://25mainstreet.com',
'http://baseballism.com',
'http://comfortableboxers.com',
'http://detroitkicks.com',
'http://quayaustralia.com.au',
'http://lifestylebyps.com',
'http://recycledfirefighter.com',
'http://piq.com',
'http://stickyholsters.com',
'http://rednecknationstrong.com',
'http://collartales.com',
'http://tinypeople.com.au',
'http://wrightwoodfurniture.com',
'http://thelittlebracompany.com',
'http://thesmartesthouse.com',
'http://inkodye.com',
'http://beardbrand.co.uk',
'http://woodies.com',
'http://reyswimwear.com',
'http://morfars.dk',
'http://florbuc.com',
'http://ztylus.com',
'http://elephantwallet.com',
'http://raisedbywolves.ca',
'http://ripnroll.com',
'http://rebel8.com',
'http://freakerusa.com',
'http://thewholedaily.com.au',
'http://hauteandrebellious.com',
'http://naturalfootgear.com',
'http://skylock.cc',
'http://archeryattack.com',
'http://victoryvape.com.au',
'http://explora.life',
'http://trendygear.us',
'http://soleusrunning.com',
'http://wocketwallet.com',
'http://leftfieldnyc.com',
'http://clae.com',
'http://sharktank.com.tw',
'http://ingodwetrustnyc.com',
'http://onlineleggingstore.com',
'http://everythingbeforeusmovie.com',
'http://shopsatan.com',
'http://brighterwhite.com.au',
'http://bodyjewelrysource.com',
'http://futgenie.com',
'http://nomorepainergonomics.com.au',
'http://annasheffield.com',
'http://matadorup.com',
'http://gotenna.com',
'http://hagensorganics.com.au',
'http://americanrag.com',
'http://gopano.com',
'http://undisputedbelts.com',
'http://littlemuffet.com',
'http://fortifiedbike.com',
'http://someplace.com.au',
'http://lecornu.com.au',
'http://sohodesignshop.com',
'http://beastmodeonline.com',
'http://routeoneapparel.com',
'http://mignon-shop.com',
'http://powerpractical.com',
'http://gymtonica.com',
'http://charmedaroma.com',
'http://youbarmanufacturing.com',
'http://radpowerbikes.com',
'http://shopmarkethq.com',
'http://helloivee.com',
'http://youpoundit.com',
'http://lizzyjames.com',
'http://mistura.com',
'http://unikitout.com',
'http://sackclothandashes.com',
'http://horizonsupply.co',
'http://adyn.co.uk',
'http://drivingtestsuccess.com',
'http://knit-purl.com',
'http://thesociallife.com',
'http://fifthelementonline.com',
'http://theyfit.co.uk',
'http://shirtloft.com',
'http://shopsocietysocial.com',
'http://amoreandsorvete.com',
'http://bentgo.com',
'http://kamasutra.com',
'http://bluetokaicoffee.com',
'http://hplustech.com',
'http://buildyourownclone.com',
'http://baendit.com',
'http://jgtechblog.com',
'http://silvermans.co.uk',
'http://elizabeth-gage.com',
'http://rockcitykicks.com',
'http://thetinkerspacks.com',
'http://nonasties.in',
'http://echodesigneroutlet.com',
'http://delongwine.com',
'http://gaminglib.com',
'http://allthingscustomized.com',
'http://permacharts.com',
'http://westwoodacresfabric.com',
'http://kigurumi.ca',
'http://rateiodeconcursos.com.br',
'http://violentlittle.com',
'http://dazzlepro.com',
'http://topbox.ca',
'http://orangeglad.com',
'http://ericaweiner.com',
'http://gammalabs.net',
'http://livingdeal.ca',
'http://pawndetroitstore.com',
'http://angelinavoloshina.com',
'http://swankblue.com',
'http://wheelwarehouse.com',
'http://uvcodesforsale.net',
'http://jadeyoga.com',
'http://amishtables.com',
'http://optimoz.com.au',
'http://kutoa.com',
'http://cardis.com',
'http://luglife.ca',
'http://helensjewels.com',
'http://petsenseonline.com',
'http://repechage.com',
'http://shophoneylace.com',
'http://ursamajorvt.com',
'http://oculosstore.com.br',
'http://vinylimpression.co.uk',
'http://shopgracieusa.com',
'http://femme-elegante.com',
'http://kanthaa.com',
'http://skateamerica.com',
'http://soleilblue.com',
'http://afends.com',
'http://littersf.com',
'http://dahmakan.com',
'http://solidandstriped.com',
'http://lurelly.com',
'http://cutcardstock.com',
'http://bhfo.com',
'http://therealdeal.co.il',
'http://giantvintage.com',
'http://getoffyouracid.com',
'http://storiarts.com',
'http://discounthockey.com',
'http://iographer.com',
'http://uvcodeshop.com',
'http://ukcustomplugs.co.uk',
'http://miniquadbros.com',
'http://shopheist.com',
'http://blackirishbooks.com',
'http://paper-crown.com',
'http://setuptheupset.com',
'http://shopflyjane.com',
'http://quitokeeto.com',
'http://sparkswarehouse.com',
'http://laconicum.co.uk',
'http://sapatore.com.br',
'http://senso.com.au',
'http://juicefromtheraw.com',
'http://howlerbros.com',
'http://hypnoticpolish.com',
'http://superkingmarkets.com',
'http://kiitosmarimekko.com',
'http://rocketbaby.it',
'http://saskiasverlag.de',
'http://boardwalkbuy.ca',
'http://aultasurf.com',
'http://tvx45.com',
'http://elevatedvaping.com',
'http://coptershop.com',
'http://freckledfawn.com',
'http://knyew.com',
'http://theairdock.com',
'http://storq.com',
'http://taiwanoolongs.com',
'http://owenandfred.com',
'http://triotablets.com',
'http://chainsawr.com',
'http://korra.in',
'http://anarchystreet.com',
'http://lafiestadeolivia.com',
'http://caitlinwilson.com',
'http://condomshop.pk',
'http://weedshop.com',
'http://richardtracybrand.com',
'http://sandmarc.com',
'http://swedishfurnitureparts.com',
'http://offdutyintimates.com',
'http://giveusyourmoneypleasethankyou-wyrd.com',
'http://28mobile.com',
'http://savvywatch.com',
'http://milehighthemes.com',
'http://solesteals.com',
'http://exhibitsworld.com',
'http://novemknight.com',
'http://brick-a-brac-uk.com',
'http://photographyandcinema.com',
'http://meanthreads.com',
'http://leatherfashiononline.com',
'http://freyrs.com',
'http://baileynelson.com.au',
'http://quoddy.com',
'http://cmeocollective.com',
'http://audiblefidelity.co.uk',
'http://colorclub.com',
'http://theholisticingredient.com',
'http://thescrubba.com',
'http://kasala.com',
'http://growlobby.com',
'http://chairs4gaming.com',
'http://lolyinthesky.com.mx',
'http://shasa.com',
'http://kenkotea.com.au',
'http://bluestockingsboutique.com',
'http://society-a.com',
'http://uponabowtique.com',
'http://omone.com',
'http://waistshaperz.com',
'http://synek.beer',
'http://wolfvsgoat.com',
'http://strangechildren.com',
'http://emmalomax.com',
'http://dfynorm.com',
'http://bemonogrammed.com',
'http://thewrld.com',
'http://gametee.co.uk',
'http://sivacycle.com',
'http://fyxation.com',
'http://zigzagstripe.com',
'http://smets.lu',
'http://skin18.com',
'http://sarahandabraham.com',
'http://soworthloving.com',
'http://thefutshop.com',
'http://supermug.co.uk',
'http://shorelinemusic.com',
'http://mixedmade.com',
'http://xdorialife.com',
'http://sacredarrowjewelry.com',
'http://shopifythemes.net',
'http://lyfetea.com',
'http://flynnskye.com',
'http://meta.watch',
'http://we-heart-this.com',
'http://keepcompany.com',
'http://christianguzman.com',
'http://weaddup.com',
'http://stoneandcloth.com',
'http://langly.co',
'http://giaresaigon.vn',
'http://wearfigs.com',
'http://gosoftwear.com',
'http://plumechocolat.com',
'http://catwalkconnection.com',
'http://zyppah.com',
'http://growlerwerks.com',
'http://biggerharderfaster.com',
'http://yourpbfriend.com',
'http://gitmanvintage.com',
'http://accessoryconcierge.com',
'http://gotpetsupplies.com',
'http://woogoing.com',
'http://swissbarefootcompany.ch',
'http://garagedoornation.com',
'http://anatomie.com',
'http://beveragesdirect.com',
'http://acaia.co',
'http://wearyourlabel.com',
'http://3sprouts.com',
'http://sexymodest.com',
'http://thelibraryoffragrance.com',
'http://aulitfinelinens.com',
'http://fluxmob.com',
'http://jasonaldean.com',
'http://allydress.com',
'http://credobeauty.com',
'http://littleletterlights.com',
'http://felersunglasses.com',
'http://elciecosmetics.com',
'http://parkersofbolton.co.uk',
'http://mineralfusion.com',
'http://purplebox.ie',
'http://qupid.com',
'http://mistamatcha.com',
'http://filastruder.com',
'http://foriapleasure.com',
'http://superfightgame.com',
'http://coco-jack.com',
'http://geekyget.com',
'http://honestlyhealthyfood.com',
'http://rugandhome.com',
'http://loopymango.com',



]




###### GOOD TEST CASES:
# www.vitamart.ca - literally just runs forever, so annoying
# azuqua.com - every single link on here is a redirect, lol

UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36'

# ALL OPTIONS: http://stackoverflow.com/questions/14227555/how-to-crawl-only-the-root-url-with-anemone
DEFAULT_OPTS = {
  :depth_limit=>1,
  :user_agent=>UA,
  :discard_page_bodies => true,
  :storage=> Anemone::Storage.PStore('pages.pstore'),
  :accept_cookies => true,
  :read_timeout => 10,
  :verbose=>true
}

#domains = ['https://vitamart.ca']   ### make sure all urls have http in beginning, else relative url errors will occur
#domains = domains.shuffle[0..25]
# domains = ['http://bexargoods.com']


# object1 = Marshal.load(File.read('../mashape/"hs-analytics"/response_object_1')); 0
# arr = object1.body['hits']['hits']; 0
# domains = []
# arr.each_with_index do |i,indx|
#   # puts 'jrb + ' + indx.to_s
#   # all sites seem to have redirect urls (and we only care about the ultimate domain so follow those)
#   if indx%1000 == 0 then puts "adding domains #{indx/1000}%" end
#   domains << 'http://'+get_domain(i['fields']['redirect'][0])
# end ; 0
# domains = domains.shuffle[0..10000]

# domains = [
#   'http://caparch.us',
#   'http://jetico.com',
#   'http://randallreilly.com',
#   'http://yesyesyes.org'
# ]




puts 'Started at: ' + Time.now.to_s
site_hash = {}
errors = {}
domains.each_with_index do |target, target_indx|



  begin
  uri = URI(target)
  #site = Site.first_or_create({ :host => uri.host }, { :created_at => Time.now })
  $stderr.puts "Scanning #{uri.host}"

  # output structure columns
  # domain
  # emails
  # twitters

  a = Anemone

  a.crawl(uri, DEFAULT_OPTS) do |anemone|

    
    anemone.on_every_page do |crawled_page|

      #if crawled_page.url.to_s.include? 'https://www.azuqua.com/solutions' then binding.pry end



      domain = get_domain(target)
      if !site_hash.has_key?(domain)
        site_hash[domain] = {}
        site_hash[domain]['twitters0'] = []
        site_hash[domain]['twitters1'] = []
        site_hash[domain]['emails0'] = []
        site_hash[domain]['emails1'] = []
        site_hash[domain]['country'] = []
        site_hash[domain]['pages_crawled'] = 0
        site_hash[domain]['redirect_pages'] = 0
      end

      puts '------------------- Domain #' + target_indx.to_s + '---------------------'
      puts crawled_page.url
      puts crawled_page.code


      # remember that by default, anemone only follows links that are in your domain (no external links, so no need for that logic)
      if ( crawled_page.code == nil || crawled_page.code >= 400 )
        next
      end


      if(site_hash[domain] )
        puts 'redirect_pages: ' + site_hash[domain]['redirect_pages'].to_s
      end

      if ( [301, 302].any? {|status| crawled_page.code == status}  )
        site_hash[domain]['redirect_pages'] += 1
        if site_hash[domain]['redirect_pages'] < 25 # if its done this >50 times, strong chance its caught in some redirect loop
          domains << crawled_page.redirect_to.to_s
        end
        next # since crawled_page.body will be nil if we keep going
      end


      depth = crawled_page.depth.to_s
      if depth.to_i > 1 then depth = '1' end


      crawled_page.body.scan(/[https?:\/\/]+[www.]*twitter.com\/[a-zA-Z0-9_]+/).each do |twitter|

        twitter = twitter.downcase
        found = ( site_hash[domain]['twitters0'] + site_hash[domain]['twitters1'] ).any? {|tw| tw.include? twitter.split('/').last }


        bad_words = ['share', 'widgets', 'intent', 'search']
        true_statements = [
          !twitter.empty?,
          !(bad_words.any?{|word| twitter.downcase.include?(word)}),
          !found,
        ]


        site_hash[domain]['twitters'+depth] += [twitter] unless true_statements.include? false

      end

      #binding.pry

      crawled_page.body.scan(/[\w\d]+[\w\d.-]@[\w\d.-]+\.\w{2,6}/).each do |address|

        address = address.downcase

        if address.empty?
          found = true
        else
          good_pages_for_emails = ['contact', 'support', 'connect']
          found_on_good_pg = good_pages_for_emails.any?{|p| crawled_page.url.to_s.downcase.include? p } ? mod_depth = '0' : mod_depth = depth
          
          if(found_on_good_pg)
            look_in_arr = site_hash[domain]['emails0']
            site_hash[domain]['emails1'].delete(address)
          else
            look_in_arr = site_hash[domain]['emails0'] + site_hash[domain]['emails1']
          end
          found = look_in_arr.any? {|em| em.include? address }
        end

        if address.include? 'email.com' then found = true end
        if address.include? 'example.com' then found = true end
        if address.include? 'domain.com' then found = true end # domain, yourdomain, mydomain
        if address.include? 'yoursite.com' then found = true end 
        if address.include? 'youremail@' then found = true end 



        if TLDS.any? {|tld| address.split('.').last == tld }          
          site_hash[domain]['emails'+mod_depth]  += [address] if !found
        end
        # if Address.first(:email => address).nil?

        #   puts 'found email ---------------------------'
        #   puts address


        #   page = Page.first_or_create(
        #     { :url => crawled_page.url.to_s },
        #     {
        #       :site => site,
        #       :created_at => Time.now
        #     }
        #   )

        #   Address.create(
        #     :email => address,
        #     :site => site,
        #     :page => page,
        #     :created_at => Time.now
        #   )

        #   puts address
        # end

      end


      if crawled_page.depth == 0 # we're on the first non-redirect page
        #### remember that on the previous ones, we wanted to scan source code
        #### for this one, we only want to scan VISIBLE TEXT (or else it gets all sorts of random numbers)
        crawled_page.doc.inner_text.scan(/[+\d()]+.[+\d()]+.\d+.\d+.\d+/).each do |num|
          begin
          parsed_val = GlobalPhone.parse(num) if (num[0] == '+') || (num.gsub(/\D/, '').size == 9) || (num.gsub(/\D/, '').size == 10)
          if parsed_val
            site_hash[domain]['country'] += [parsed_val.territory.name] unless site_hash[domain]['country'].include? parsed_val.territory.name
          end
          rescue 
            # binding.pry
          end
        end
      end



      site_hash[domain]['pages_crawled'] += 1



    end


  end
  rescue Exception => e

    puts "error ---------------------------"
    puts e



  end
  puts ''
  puts ''
  puts ''

  # delete the pstore for this domain, without this will get REALLY slow REALLY fast
  File.delete('pages.pstore') if File.exists? 'pages.pstore'



end






File.open("site_hash", 'wb') {|f| f.write(Marshal.dump(site_hash)) }
File.open("errors", 'wb') {|f| f.write(Marshal.dump(errors)) }
puts 'Completed at: ' + Time.now.to_s


binding.pry

